//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrinanceLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrinanceLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    BNB Commission: {0}.
        /// </summary>
        internal static string ArbitrageCommission {
            get {
                return ResourceManager.GetString("ArbitrageCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    {0} Delta: {0}{1} ({2}%).
        /// </summary>
        internal static string ArbitrageDelta {
            get {
                return ResourceManager.GetString("ArbitrageDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Deltas.
        /// </summary>
        internal static string ArbitrageDeltas {
            get {
                return ResourceManager.GetString("ArbitrageDeltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCARDED: the age ({0}ms) is greater than the {1}ms threshold..
        /// </summary>
        internal static string ArbitrageDiscardedAge {
            get {
                return ResourceManager.GetString("ArbitrageDiscardedAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCARDED: one or more reference assets are currently involved in another execution..
        /// </summary>
        internal static string ArbitrageDiscardedAssets {
            get {
                return ResourceManager.GetString("ArbitrageDiscardedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCARDED: the executions cap of {0} has been reached..
        /// </summary>
        internal static string ArbitrageDiscardedCap {
            get {
                return ResourceManager.GetString("ArbitrageDiscardedCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCARDED: more than one execution has been attempted during the last second..
        /// </summary>
        internal static string ArbitrageDiscardedCooldown {
            get {
                return ResourceManager.GetString("ArbitrageDiscardedCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCARDED: the profit is less than the {0}% threshold..
        /// </summary>
        internal static string ArbitrageDiscardedProfit {
            get {
                return ResourceManager.GetString("ArbitrageDiscardedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Expected Conversion: {0} {1} -&gt; {2} {3}.
        /// </summary>
        internal static string ArbitrageExpectedConversion {
            get {
                return ResourceManager.GetString("ArbitrageExpectedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILURE: arbitrage execution failed using the {0} strategy: {1}..
        /// </summary>
        internal static string ArbitrageFailed {
            get {
                return ResourceManager.GetString("ArbitrageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ARBITRAGE \&quot;{0}\&quot; Profit: {1}%].
        /// </summary>
        internal static string ArbitrageFound {
            get {
                return ResourceManager.GetString("ArbitrageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Observed Conversion: {0} {1} -&gt; {2} {3}.
        /// </summary>
        internal static string ArbitrageObservedConversion {
            get {
                return ResourceManager.GetString("ArbitrageObservedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Others.
        /// </summary>
        internal static string ArbitrageOthers {
            get {
                return ResourceManager.GetString("ArbitrageOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Step {0}.
        /// </summary>
        internal static string ArbitrageStep {
            get {
                return ResourceManager.GetString("ArbitrageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS: arbitrage execution succeded using the {0} strategy:.
        /// </summary>
        internal static string ArbitrageSucceded {
            get {
                return ResourceManager.GetString("ArbitrageSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCES: loading failed, {0}..
        /// </summary>
        internal static string BalancesKO {
            get {
                return ResourceManager.GetString("BalancesKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCES: loading succeded, {0} wallet{1} found:.
        /// </summary>
        internal static string BalancesOK {
            get {
                return ResourceManager.GetString("BalancesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCES: loading succeded, no balances found..
        /// </summary>
        internal static string BalancesOK0 {
            get {
                return ResourceManager.GetString("BalancesOK0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file path specified..
        /// </summary>
        internal static string ConfigurationFileInvalid {
            get {
                return ResourceManager.GetString("ConfigurationFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file could not be found..
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTIVITY TEST: connection failed, {0}..
        /// </summary>
        internal static string ConnectivityKO {
            get {
                return ResourceManager.GetString("ConnectivityKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle completed in {0}ms, average duration of {1}..
        /// </summary>
        internal static string CycleCompleted {
            get {
                return ResourceManager.GetString("CycleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle skipped, the threshold of {0}ms has been exceeded..
        /// </summary>
        internal static string CycleSkipped {
            get {
                return ResourceManager.GetString("CycleSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths are too shallow..
        /// </summary>
        internal static string DepthsTooShallow {
            get {
                return ResourceManager.GetString("DepthsTooShallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange engine has not been initialized..
        /// </summary>
        internal static string EngineNotInitialized {
            get {
                return ResourceManager.GetString("EngineNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXCHANGE INITIALIZATION].
        /// </summary>
        internal static string ExchangeInitialization {
            get {
                return ResourceManager.GetString("ExchangeInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base asset specified..
        /// </summary>
        internal static string InvalidBaseAsset {
            get {
                return ResourceManager.GetString("InvalidBaseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exchange defined in the configuration file..
        /// </summary>
        internal static string InvalidConfigurationExchange {
            get {
                return ResourceManager.GetString("InvalidConfigurationExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DATA.STAGGER parameter must be greater than or equal to {0}..
        /// </summary>
        internal static string InvalidDataStagger {
            get {
                return ResourceManager.GetString("InvalidDataStagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dust decimals value must be greater than or equal to 0..
        /// </summary>
        internal static string InvalidDustDecimals {
            get {
                return ResourceManager.GetString("InvalidDustDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enumerator value..
        /// </summary>
        internal static string InvalidEnumeratorValue {
            get {
                return ResourceManager.GetString("InvalidEnumeratorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The INVESTMENT.BASE_ASSET parameter is not valid..
        /// </summary>
        internal static string InvalidInvestmentBaseAsset {
            get {
                return ResourceManager.GetString("InvalidInvestmentBaseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The INVESTMENT.MAXIMUM parameter must be greater than 0..
        /// </summary>
        internal static string InvalidInvestmentMaximum {
            get {
                return ResourceManager.GetString("InvalidInvestmentMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The INVESTMENT.MINIMUM parameter must be greater than 0..
        /// </summary>
        internal static string InvalidInvestmentMinimum {
            get {
                return ResourceManager.GetString("InvalidInvestmentMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The INVESTMENT.MINIMUM parameter must be less than or equal to the INVESTMENT.MAXIMUM parameter..
        /// </summary>
        internal static string InvalidInvestmentMinimumMaximum {
            get {
                return ResourceManager.GetString("InvalidInvestmentMinimumMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The INVESTMENT.STEP parameter must be greater than 0..
        /// </summary>
        internal static string InvalidInvestmentStep {
            get {
                return ResourceManager.GetString("InvalidInvestmentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough steps between INVESTMENT.MINIMUM and INVESTMENT.MAXIMUM..
        /// </summary>
        internal static string InvalidInvestmentSteps {
            get {
                return ResourceManager.GetString("InvalidInvestmentSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The KEYS.API parameter is not valid..
        /// </summary>
        internal static string InvalidKeysApi {
            get {
                return ResourceManager.GetString("InvalidKeysApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The KEYS.SECRET parameter is not valid..
        /// </summary>
        internal static string InvalidKeysSecret {
            get {
                return ResourceManager.GetString("InvalidKeysSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid leg specified..
        /// </summary>
        internal static string InvalidLeg {
            get {
                return ResourceManager.GetString("InvalidLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position specified..
        /// </summary>
        internal static string InvalidPosition {
            get {
                return ResourceManager.GetString("InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quote asset specified..
        /// </summary>
        internal static string InvalidQuoteAsset {
            get {
                return ResourceManager.GetString("InvalidQuoteAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference asset specified..
        /// </summary>
        internal static string InvalidReferenceAsset {
            get {
                return ResourceManager.GetString("InvalidReferenceAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid step specified..
        /// </summary>
        internal static string InvalidStep {
            get {
                return ResourceManager.GetString("InvalidStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid symbol specified..
        /// </summary>
        internal static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.CYCLES_DELAY parameter must be greater than or equal to {0}..
        /// </summary>
        internal static string InvalidTradingCyclesDelay {
            get {
                return ResourceManager.GetString("InvalidTradingCyclesDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.EXECUTIONS_CAP parameter must be greater than or equal to 0..
        /// </summary>
        internal static string InvalidTradingExecutionsCap {
            get {
                return ResourceManager.GetString("InvalidTradingExecutionsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.POSITIONS parameter must contain 3 positions and cannot be all the same..
        /// </summary>
        internal static string InvalidTradingPositions {
            get {
                return ResourceManager.GetString("InvalidTradingPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.STRATEGY parameter, when set to PARALLEL, requires defining a non-empty TRADING.WHITELIST parameter..
        /// </summary>
        internal static string InvalidTradingStrategyParallel {
            get {
                return ResourceManager.GetString("InvalidTradingStrategyParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.TAKER_FEE parameter must be greater than or equal to 0..
        /// </summary>
        internal static string InvalidTradingTakerFee {
            get {
                return ResourceManager.GetString("InvalidTradingTakerFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.THRESHOLD_AGE parameter must be greater than or equal to {0}..
        /// </summary>
        internal static string InvalidTradingThresholdAge {
            get {
                return ResourceManager.GetString("InvalidTradingThresholdAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.THRESHOLD_PROFIT parameter must be greater than 0..
        /// </summary>
        internal static string InvalidTradingThresholdProfit {
            get {
                return ResourceManager.GetString("InvalidTradingThresholdProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.WHITELIST parameter, when defined, must include only valid assets..
        /// </summary>
        internal static string InvalidTradingWhitelistAssets {
            get {
                return ResourceManager.GetString("InvalidTradingWhitelistAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TRADING.WHITELIST parameter, when defined, must include the base asset..
        /// </summary>
        internal static string InvalidTradingWhitelistBaseAsset {
            get {
                return ResourceManager.GetString("InvalidTradingWhitelistBaseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN: authentication failed, {0}..
        /// </summary>
        internal static string LoginKO {
            get {
                return ResourceManager.GetString("LoginKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN: authentication succeded..
        /// </summary>
        internal static string LoginOK {
            get {
                return ResourceManager.GetString("LoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTIVITY TEST: connection succeded, average ping of {0}ms..
        /// </summary>
        internal static string MessageConnectivityOK {
            get {
                return ResourceManager.GetString("MessageConnectivityOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No asks available..
        /// </summary>
        internal static string NoAvailableAsks {
            get {
                return ResourceManager.GetString("NoAvailableAsks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bids available..
        /// </summary>
        internal static string NoAvailableBids {
            get {
                return ResourceManager.GetString("NoAvailableBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spread between bid and ask..
        /// </summary>
        internal static string NoBidAskSpread {
            get {
                return ResourceManager.GetString("NoBidAskSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No triangular relationships found..
        /// </summary>
        internal static string NoTriangularRelationships {
            get {
                return ResourceManager.GetString("NoTriangularRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BOOKS: initialization failed, {0}..
        /// </summary>
        internal static string OrderBooksKO {
            get {
                return ResourceManager.GetString("OrderBooksKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BOOKS: initialization succeded, {0} websocket{1} subscribed..
        /// </summary>
        internal static string OrderBooksOK {
            get {
                return ResourceManager.GetString("OrderBooksOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is under maintenance..
        /// </summary>
        internal static string ServerMaintenance {
            get {
                return ResourceManager.GetString("ServerMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not answer a ping request..
        /// </summary>
        internal static string ServerPing {
            get {
                return ResourceManager.GetString("ServerPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADES: computation failed, {0}..
        /// </summary>
        internal static string TradesKO {
            get {
                return ResourceManager.GetString("TradesKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADES: computation succeded, {0} triangular relationship{1} found..
        /// </summary>
        internal static string TradesOK {
            get {
                return ResourceManager.GetString("TradesOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * TRADING SESSION STARTED AT {0} *.
        /// </summary>
        internal static string TradingSession {
            get {
                return ResourceManager.GetString("TradingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null token to {0}..
        /// </summary>
        internal static string UnhandledTokenNull {
            get {
                return ResourceManager.GetString("UnhandledTokenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled token {0} in {1}..
        /// </summary>
        internal static string UnhandledTokenType {
            get {
                return ResourceManager.GetString("UnhandledTokenType", resourceCulture);
            }
        }
    }
}
